favicon: /favicon.ico

banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=

githubCorner: '<a href="https://github.com/Ghostasoul/ghostasoul.github.io/tree/webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 测试页面
    icon: far fa-star
    config: testPage
  - name: 常用推荐
    icon: far fa-star
    config: hotTools
  - name: 码农专区
    icon: fas fa-tools
    submenu:
      - name: 代码托管
        icon: fas fa-tools
        config: gitHosting
      - name: 静态网站
        icon: fas fa-tools
        config: staticWebsite
      - name: 云服务器
        icon: fas fa-blog
        config: cloudServer

  - name: 教育学习
    icon: fas fa-tools
    submenu:
      - name: 博客站点
        icon: fas fa-tools
        config: blogSite
      - name: 书籍文档
        icon: fas fa-tools
        config: bookDocument
      - name: 视频教程
        icon: fas fa-blog
        config: videoTutorial
      - name: 考研相关
        icon: fas fa-blog
        config: postGraduate

  - name: 社区论坛
    icon: fas fa-tools
    submenu:
      - name: 技术官网
        icon: fas fa-tools
        config: openSource
      - name: 技术社区
        icon: fas fa-tools
        config: technicalCommunity
      - name: 其他社区
        icon: fas fa-blog
        config: otherCommunity

  - name: 休闲娱乐
    icon: fas fa-tools
    submenu:
      - name: 影音视频
        icon: fas fa-tools
        config: videoAudio
      - name: 游戏竞技
        icon: fas fa-tools
        config: games
      - name: 新闻平台
        icon: fas fa-blog
        config: news

  - name: 工具集合
    icon: fas fa-tools
    submenu:
      - name: 素材资源
        icon: fas fa-tools
        config: material
      - name: 网络加速
        icon: fas fa-tools
        config: internetSpeed
      - name: 实用工具
        icon: fas fa-tools
        config: usefulTools

  - name: Mac专区
    icon: fas fa-tools
    config: macZone

  - name: AI相关
    icon: fas fa-tools
    config: aiTools

testPage:
  - name: Child Page
    url: /child
    img: /images/logos/myblog.png
    description: 子页面测试

## 常用推荐
hotTools:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: MyBlog
    url: https://ghostasoul.github.io/myblog
    img: /images/logos/myblog.png
    description: 个人分享知识的博客
  - name: MyVitPress
    url: https://ghostasoul.github.io/myvitpress
    img: /images/logos/myvitpress.png
    description: 个人文档网站
  - name: Java知识体系
    url: https://pdai.tech
    img: /images/logos/pdai.gif
    description: Java全栈知识体系
  - name: 微信读书
    url: https://weread.qq.com
    img: /images/logos/weixindushu.jpg
    description: 微信读书是一款基于微信平台的网络文学阅读产品。
  - name: 奈飞工厂
    url: https://www.netflixgc.com
    img: /images/logos/netflix.png
    description: 致力于免费提供高清影视内容的全球视频平台。
  - name: 6V电影网
    url: https://www.hao6v.tv
    img: /images/logos/6v.gif
    description: 免费电影电视剧下载网站。
  - name: MacWK
    url: https://macwk.cn
    img: /images/logos/macwk.png
    description: 精品Mac软件下载。


## 代码托管
gitHosting:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://gitee.com
    img: /images/logos/gitee.jpeg
    description: 面向开源及私有软件项目的托管平台。
  - name: GitCode
    url: https://gitcode.net/explore
    img: /images/logos/gitcode.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Bitbucket
    url: https://bitbucket.org/
    img: /images/logos/bitbucket.png
    description: 面向开源及私有软件项目的托管平台。
  - name: GitLab
    url: https://about.gitlab.com
    img: /images/logos/gitlab.webp
    description: 面向开源及私有软件项目的托管平台。

## 静态网站
staticWebsite:
  - name: Webify
    url: https://webify.cloudbase.net
    img: /images/logos/tengxunyun.webp
    description: 专为web开发者打造的静态网站托管服务。
  - name: Netlify
    url: https://app.netlify.com
    img: /images/logos/netlify.webp
    description: 组合式Web平台。
  - name: Vercel
    url: https://vercel.com
    img: /images/logos/vercel.webp
    description: 通过前端云构建和服务器端计算，为开发人员提供快速、可靠的静态网站托管服务。
  - name: Solo
    url: https://b3log.org/solo/
    img: /images/logos/solo.png
    description: Java开源博客系统

## 云服务器
cloudServer:
  - name: 阿里云
    url: https://www.aliyun.com
    img: /images/logos/aliyun.jpg
    description: 上云就上阿里云，云服务器、云数据库、云存储、云函数、云容器等一应俱全。
  - name: 腾讯云
    url: https://cloud.tencent.com
    img: /images/logos/tengxunyun.webp
    description: 产业智变，云启未来。
  - name: 华为云
    url: https://www.huaweicloud.com
    img: /images/logos/huaweiyun.png
    description: 共建智能世界，构建智慧生活。
  - name: 京东云
    url: https://www.jdcloud.com
    img: /images/logos/jingdongyun.jpg
    description: 京东科技集团旗下公有云服务提供商。
  - name: 雨云
    url: https://www.rainyun.com/home
    img: /images/logos/yuyun.png
    description: 新一代云服务提供商。
  - name: 乔拓云建站
    url: https://www.webportal.top
    img: /images/logos/qiaotuoyun.png
    description: 创建网站，小程序的服务商。

## 博客站点
blogSite:
  - name: MyBlog
    url: https://ghostasoul.github.io/myblog
    img: /images/logos/myblog.png
    description: 个人分享知识的博客
  - name: MyVitPress
    url: https://ghostasoul.github.io/myvitpress
    img: /images/logos/myvitpress.png
    description: 个人文档网站
  - name: Java知识体系
    url: https://pdai.tech
    img: /images/logos/pdai.gif
    description: Java全栈知识体系
  - name: Bugstack
    url: https://bugstack.cn
    img: /images/logos/bugstack.png
    description: bugstack 虫洞栈
  - name: Java进阶知识扫盲
    url: https://doocs.github.io/advanced-java/#/
    img: /images/logos/advancedjava.png
    description: 互联网 Java 工程师进阶知识完全扫盲
  - name: JavaGuide
    url: https://javaguide.cn
    img: /images/logos/javaguide.svg
    description: Java 程序员所需要掌握的核心知识
  - name: Java知识图谱
    url: https://www.altitude.xin/blog/home/#/
    img: /images/logos/saitai.png
    description: Java 相关的知识博客
  - name: Road To Coding
    url: https://www.r2coding.com/#/
    img: /images/logos/r2coding.png
    description: 编程自学之路
  - name: 代码随想录
    url: https://programmercarl.com
    img: /images/logos/daimasuixianglu.png
    description: 认准代码随想录，学习算法不迷路
  - name: 吴师兄学算法
    url: https://blog.algomooc.com
    img: /images/logos/wushixiong.png
    description: 从初学者到算法专家，学习算法，刷题，刷题，刷题，提升算法能力
  - name: JVM底层原理
    url: https://doocs.github.io/jvm/
    img: /images/logos/jvm.png
    description: JVM 底层原理最全知识总结

## 书籍文档
bookDocument:
  - name: 微信读书
    url: https://weread.qq.com
    img: /images/logos/weixindushu.jpg
    description: 微信读书是一款基于微信平台的网络文学阅读产品。
  - name: 链滴
    url: https://ld246.com
    img: /images/logos/liandi.png
    description: 记录生活，链接未来。
  - name: 豆瓣读书
    url: https://book.douban.com
    img: /images/logos/douban.jpg
    description: 豆瓣读书，一个记录书评的网站。postGraduate
  - name: 欢乐图书馆
    url: https://www.thinkdoc.vip/#google_vignette
    img: /images/logos/thinkdoc.png
    description: 收录最优质的电子图书，提供最方便的阅读体验。
  - name: GitBook
    url: https://git-scm.com/book/zh/v2
    img: /images/logos/gitbook.png
    description: 讲解Git最棒的电子书。

## 视频教程
videoTutorial:
  - name: 慕课网
    url: https://www.imooc.com
    img: /images/logos/imooc.png
    description: 程序员的梦工厂。

## 考研相关
postGraduate:
  - name: 研招网
    url: https://yz.chsi.com.cn
    img: /images/logos/yanzhaowang.png
    description: 中国研究生招生信息网。

## 技术官网
openSource:
  - name: Spring
    url: https://spring.io
    img: /images/logos/spring.webp
    description: Spring框架官网。
  - name: Apache
    url: https://www.apache.org
    img: /images/logos/apache.jpg
    description: Apache基金会官网。
  - name: Sentinel
    url: https://sentinelguard.io/zh-cn/index.html
    img: /images/logos/sentinel.png
    description: 面向分布式、多语言异构化服务架构的流量治理组件
  - name: Nextjs
    url: https://nextjs.org/
    img: /images/logos/nextjs.svg
    description: 网络的React框架。
  - name: Nodejs
    url: https://nodejs.org/
    img: /images/logos/nodejs.png
    description: 免费、开源、跨平台的JavaScript运行时环境，允许开发人员创建服务器、Web应用程序、命令行工具和脚本。

## 技术社区
technicalCommunity:
  - name: 简书
    url: https://www.jianshu.com
    img: /images/logos/jianshu.png
    description: 简书-创作你的创作，发现你的发现。
  - name: 稀土
    url: https://juejin.cn
    img: /images/logos/xitu.png
    description: 代码不止，掘金不停。
  - name: CSDN
    url: https://www.csdn.net
    img: /images/logos/csdn.jpg
    description: 专业技术社区。
  - name: 牛客网
    url: https://www.nowcoder.com
    img: /images/logos/niuke.png
    description: 找工作，找面试，找实习，找工作。
  - name: W2Solo
    url: https://www.w2solo.com
    img: /images/logos/w2solo.png
    description: 独立开发者社区。
  - name: 京东云
    url: https://developer.jdcloud.com
    img: /images/logos/jdcloud.png
    description: 京东云-开发者社区。

## 其他社区
otherCommunity:
  - name: 写作社区
    url: https://xie.infoq.cn
    img: /images/logos/xiezuo.png
    description: 专业技术博客社区。

## 影音视频
videoAudio:
  - name: YouTube
    url: https://www.youtube.com/
    img: /images/logos/youtube.svg
    description: 全球最大的视频分享平台。
  - name: 奈飞工厂
    url: https://www.netflixgc.com
    img: /images/logos/netflix.png
    description: 致力于免费提供高清影视内容的全球视频平台。
  - name: 6V电影网
    url: https://www.hao6v.tv
    img: /images/logos/6v.gif
    description: 免费电影电视剧下载网站。
  - name: 可可影视
    url: https://www.keke6.app
    img: /images/logos/kekeyingshi.png
    description: 你想看的都有。
  - name: 布谷TV
    url: https://www.bugutv.org
    img: /images/logos/bugu.png
    description: 免费4K电影下载网站。
  - name: 影视森林
    url: http://www.549.tv
    img: /images/logos/yingshisenlin.png
    description: 众多影视网站的聚合。

## 游戏竞技
games:
  - name: PS游戏百宝箱
    url: https://www.memechen.com
    img: /images/logos/chenchen.png
    description: PS主机游戏资讯站
  - name: 游民星空
    url: https://www.gamersky.com
    img: /images/logos/gamersky.png
    description: 大型单机游戏门户网站。
  - name: Fandom
    url: https://www.fandom.com
    img: /images/logos/fandom.png
    description: 游戏资料网站。
  - name: 布锅锅联盟宇宙
    url: https://buguoguo.cn
    img: /images/logos/buguoguolol.png
    description: 英雄联盟资料网站。

## 新闻平台
news:
  - name: 微博
    url: https://weibo.com/
    img: /images/logos/weibo.jpg
    description: 随时随地发现新鲜事。
  - name: 今日头条
    url: https://www.toutiao.com
    img: /images/logos/toutiao.jpg
    description: 你关心的才是头条。

## 素材资源
material:
  - name: 矢量图标网
    url: https://igoutu.cn
    img: /images/logos/icons8.png
    description: 面向开源及私有软件项目的托管平台。
  - name: 60logo
    url: https://www.60logo.com
    img: /images/logos/60logo.png
    description: 海量品牌LOGO下载。
  - name: GameIcons
    url: https://game-icons.net
    img: /images/logos/gameIcons.svg
    description: 游戏主题图标素材。
  - name: Pexels
    url: https://www.pexels.com
    img: /images/logos/pexels.png
    description: 免费高质量图片素材。
  - name: Unsplash
    url: https://unsplash.com
    img: /images/logos/unsplash.png
    description: 免费无版权高清图片。
  - name: 搞定设计
    url: https://www.gaoding.com
    img: /images/logos/gaoding.svg
    description: 做图做视频必备。
  - name: 微软PPT模版
    url: https://www.officeplus.cn/PPT/template/
    img: /images/logos/weiruanppt.svg
    description: 微软官方PPT模板免费下载。
  - name: 一网一匠
    url: https://ywyj.cn
    img: /images/logos/ywyj.png
    description: 一起发现有趣产品。


## 网络加速
internetSpeed:
  - name: Steam++
    url: https://steampp.net
    img: /images/logos/steam++.png
    description: 可以加速Steam和Origin游戏的网络加速器。

## 实用工具
usefulTools:
  - name: 实用工具大全
    url: https://tool.520101.com
    img: /images/logos/tool520101.gif
    description: 很全的在线实用工具网站。
  - name: 在线代码格式化
    url: https://tool.oschina.net/codeformat/xml/
    img: /images/logos/tooloschina.jpg
    description: 在线代码格式化工具。

## Mac专区
macZone:
  - name: MacWK
    url: https://macwk.cn
    img: /images/logos/macwk.png
    description: 精品Mac软件下载。
  - name: 腾讯柠檬
    url: https://lemon.qq.com/lab/
    img: /images/logos/ningmeng.png
    description: 收录免费、正版、好用的Mac软件。

## AI相关
aiTools:
  - name: ChatGPT
    url: https://chat.openai.com
    img: /images/logos/chatgpt.png
    description: 很好用的AI工具···

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: ZhangYuShuo
    url: https://ghostasoul.github.io
    img: /images/logos/myblog.png
    description: 天道酬勤
    html: '<br /><blockquote><p>本站是<a href="https://github.com/Ghostasoul">ZhangYuShuo</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2024

busuanzi:
  enable: true
  position: footer # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css

