favicon: /favicon.ico

banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  - name: Chinese
    default: true
    icon: flag-cn
    index: /index.html

search: true

userDefinedSearchData:
  custom: false
  thisSearch: https://www.baidu.com/s?wd=
  thisSearchIcon: url(https://www.baidu.com/favicon.ico)
  hotStatus: true
  data:
    - name: 百度
      img: url(https://www.baidu.com/favicon.ico)
      url: https://www.baidu.com/s?wd=

githubCorner: '<a href="https://github.com/Ghostasoul/ghostasoul.github.io/tree/webstack" class="github-corner" aria-label="View source on GitHub"><svg width="80" height="80" viewBox="0 0 250 250" style="fill:#151513; color:#fff; position: absolute; top: 0; border: 0; right: 0;" aria-hidden="true"><path d="M0,0 L115,115 L130,115 L142,142 L250,250 L250,0 Z"></path><path d="M128.3,109.0 C113.8,99.7 119.0,89.6 119.0,89.6 C122.0,82.7 120.5,78.6 120.5,78.6 C119.2,72.0 123.4,76.3 123.4,76.3 C127.3,80.9 125.5,87.3 125.5,87.3 C122.9,97.6 130.6,101.9 134.4,103.2" fill="currentColor" style="transform-origin: 130px 106px;" class="octo-arm"></path><path d="M115.0,115.0 C114.9,115.1 118.7,116.5 119.8,115.4 L133.7,101.6 C136.9,99.2 139.9,98.4 142.2,98.6 C133.8,88.0 127.5,74.4 143.8,58.0 C148.5,53.4 154.0,51.2 159.7,51.0 C160.3,49.4 163.2,43.6 171.4,40.1 C171.4,40.1 176.1,42.5 178.8,56.2 C183.1,58.6 187.2,61.8 190.9,65.4 C194.5,69.0 197.7,73.2 200.1,77.6 C213.8,80.2 216.3,84.9 216.3,84.9 C212.7,93.1 206.9,96.0 205.4,96.6 C205.1,102.4 203.0,107.8 198.3,112.5 C181.9,128.9 168.3,122.5 157.7,114.1 C157.9,116.9 156.7,120.9 152.7,124.9 L141.0,136.5 C139.8,137.7 141.6,141.9 141.8,141.8 Z" fill="currentColor" class="octo-body"></path></svg></a><style>.github-corner:hover .octo-arm{animation:octocat-wave 560ms ease-in-out}@keyframes octocat-wave{0%,100%{transform:rotate(0)}20%,60%{transform:rotate(-25deg)}40%,80%{transform:rotate(10deg)}}@media (max-width:500px){.github-corner:hover .octo-arm{animation:none}.github-corner .octo-arm{animation:octocat-wave 560ms ease-in-out}}</style>'

expandAll: false
menu:
  - name: 测试页面
    icon: far fa-star
    config: testPage
  - name: 常用推荐
    icon: far fa-star
    config: hotTools
  - name: 码农专区
    icon: fas fa-tools
    submenu:
      - name: 代码托管
        icon: fas fa-tools
        config: gitHosting
      - name: 静态网站
        icon: fas fa-tools
        config: staticWebsite
      - name: 云服务器
        icon: fas fa-blog
        config: cloudServer

  - name: 教育学习
    icon: fas fa-tools
    submenu:
      - name: 博客站点
        icon: fas fa-tools
        config: blogSite
      - name: 书籍文档
        icon: fas fa-tools
        config: bookDocument
      - name: 视频教程
        icon: fas fa-blog
        config: videoTutorial

  - name: 社区论坛
    icon: fas fa-tools
    submenu:
      - name: 开源社区
        icon: fas fa-tools
        config: openSource
      - name: 技术社区
        icon: fas fa-tools
        config: technicalCommunity
      - name: 其他社区
        icon: fas fa-blog
        config: otherCommunity

  - name: 休闲娱乐
    icon: fas fa-tools
    submenu:
      - name: 影音视频
        icon: fas fa-tools
        config: videoAudio
      - name: 游戏竞技
        icon: fas fa-tools
        config: games
      - name: 新闻平台
        icon: fas fa-blog
        config: news

  - name: 工具集合
    icon: fas fa-tools
    submenu:
      - name: 素材资源
        icon: fas fa-tools
        config: material

  - name: Mac专区
    icon: fas fa-tools
    config: macZone

testPage:
  - name: Child Page
    url: /child
    img: /images/logos/myblog.png
    description: 子页面测试

## 代码托管
gitHosting:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://gitee.com
    img: /images/logos/gitee.jpeg
    description: 面向开源及私有软件项目的托管平台。
  - name: GitCode
    url: https://gitcode.net/explore
    img: /images/logos/gitcode.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Bitbucket
    url: https://bitbucket.org/
    img: /images/logos/bitbucket.png
    description: 面向开源及私有软件项目的托管平台。
  - name: GitLab
    url: https://about.gitlab.com
    img: /images/logos/gitlab.webp
    description: 面向开源及私有软件项目的托管平台。

## 静态网站
staticWebsite:
  - name: Webify
    url: https://webify.cloudbase.net
    img: /images/logos/tengxunyun.webp
    description: 专为web开发者打造的静态网站托管服务。
  - name: Netlify
    url: https://app.netlify.com
    img: /images/logos/netlify.webp
    description: 组合式Web平台。
  - name: Vercel
    url: https://vercel.com
    img: /images/logos/vercel.webp
    description: 通过前端云构建和服务器端计算，为开发人员提供快速、可靠的静态网站托管服务。

## 云服务器
cloudServer:
  - name: 阿里云
    url: https://www.aliyun.com
    img: /images/logos/aliyun.jpg
    description: 上云就上阿里云，云服务器、云数据库、云存储、云函数、云容器等一应俱全。
  - name: 腾讯云
    url: https://cloud.tencent.com
    img: /images/logos/tengxunyun.webp
    description: 产业智变，云启未来。
  - name: 华为云
    url: https://www.huaweicloud.com
    img: /images/logos/huaweiyun.png
    description: 共建智能世界，构建智慧生活。
  - name: 京东云
    url: https://www.jdcloud.com
    img: /images/logos/jingdongyun.jpg
    description: 京东科技集团旗下公有云服务提供商。

## 博客站点
blogSite:
  - name: MyBlog
    url: https://ghostasoul.github.io/myblog
    img: /images/logos/myblog.png
    description: 个人分享知识的博客
  - name: MyVitPress
    url: https://ghostasoul.github.io/myvitpress
    img: /images/logos/myvitpress.png
    description: 个人文档网站
  - name: Java知识体系
    url: https://pdai.tech
    img: /images/logos/pdai.gif
    description: Java全栈知识体系
  - name: Bugstack
    url: https://bugstack.cn
    img: /images/logos/bugstack.png
    description: bugstack 虫洞栈
  - name: Java进阶知识扫盲
    url: https://doocs.github.io/advanced-java/#/
    img: /images/logos/advancedjava.png
    description: 互联网 Java 工程师进阶知识完全扫盲
  - name: Java学习 + 面试指南
    url: https://javaguide.cn
    img: /images/logos/javaguide.svg
    description: Java 程序员所需要掌握的核心知识
  - name: Java知识图谱
    url: https://www.altitude.xin/blog/home/#/
    img: /images/logos/saitai.png
    description: Java 相关的知识博客
  - name: Road To Coding
    url: https://www.r2coding.com/#/
    img: /images/logos/r2coding.png
    description: 编程自学之路

## 书籍文档
bookDocument:
  - name: 微信读书
    url: https://weread.qq.com
    img: /images/logos/weixindushu.jpg
    description: 微信读书是一款基于微信平台的网络文学阅读产品。

## 视频教程
videoTutorial:
  - name: 慕课网
    url: https://www.imooc.com
    img: /images/logos/imooc.png
    description: 程序员的梦工厂。

## 开源社区
openSource:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://getee.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

## 技术社区
technicalCommunity:
  - name: 简书
    url: https://www.jianshu.com
    img: /images/logos/jianshu.png
    description: 简书-创作你的创作，发现你的发现。
  - name: 稀土
    url: https://juejin.cn
    img: /images/logos/xitu.png
    description: 代码不止，掘金不停。
  - name: CSDN
    url: https://www.csdn.net
    img: /images/logos/csdn.jpg
    description: 专业技术社区。

## 其他社区
otherCommunity:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://getee.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

## 影音视频
videoAudio:
  - name: YouTube
    url: https://www.youtube.com/
    img: /images/logos/youtube.svg
    description: 全球最大的视频分享平台。
  - name: 奈飞工厂
    url: https://www.netflixgc.com
    img: /images/logos/netflix.png
    description: 致力于免费提供高清影视内容的全球视频平台。
  - name: 6V电影网
    url: https://www.hao6v.tv
    img: /images/logos/6v.gif
    description: 免费电影电视剧下载网站。
  - name: 可可影视
    url: https://www.keke6.app
    img: /images/logos/kekeyingshi.png
    description: 你想看的都有。

## 游戏竞技
games:
  - name: PS游戏百宝箱
    url: https://www.memechen.com
    img: /images/logos/chenchen.png
    description: PS主机游戏资讯站
  - name: 游民星空
    url: https://www.gamersky.com
    img: /images/logos/gamersky.png
    description: 大型单机游戏门户网站。

## 新闻平台
news:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://getee.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

## 素材资源
material:
  - name: 矢量图标网
    url: https://igoutu.cn
    img: /images/logos/icons8.png
    description: 面向开源及私有软件项目的托管平台。
  - name: 60logo
    url: https://www.60logo.com
    img: /images/logos/60logo.png
    description: 海量品牌LOGO下载。
  - name: GameIcons
    url: https://game-icons.net
    img: /images/logos/gameIcons.svg
    description: 游戏主题图标素材。

## Mac专区
macZone:
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Github
    url: https://github.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。
  - name: Gitee
    url: https://getee.com/
    img: /images/logos/github.png
    description: 面向开源及私有软件项目的托管平台。

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 关于本站
    html: '<blockquote><p>本站是hexo主题<a href="https://github.com/HCLonely/hexo-theme-webstack">hexo-theme-webstack</a>的demo站。</p></blockquote>'
  webmaster:
    head: 关于站长
    name: HCLonely
    url: https://blog.hclonely.com/
    img: /images/logos/myblog.png
    description: 懒人一个
    html: '<br /><blockquote><p>本站是<a href="https://github.com/HCLonely">HCLonely</a>基于<a href="https://github.com/WebStackPage/WebStackPage.github.io">WebStackPage</a>项目做的一款<a href="https://hexo.io/">Hexo</a>主题。</p></blockquote>'

since: 2024

busuanzi:
  enable: true
  position: footer # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->
  body: |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css

